export * from './H1.type'
export * from './H2.type'
export * from './H3.type'
export * from './Title.type'
export * from './Subtitle.type'
export * from './Text.type'
export * from './Section.type'
export * from './Tag.type'
